### ISSUE TITLE
using a geofence to trip / untrip a reactor virtual sensor?

### ISSUE THREAD

**Issue by connor992** [toggledbits/Reactor#10]
Hey ! Just discovered reactor, loving it! Think it might be just what I'm looking for!

I didn't see this, so don't know if it supports yet... but I'm looking to be able to use the entry or exit of a geofence to trip a virtual sensor. Right now, vera's native geofencing flips a house mode to **away** only if *All* geofence users leave the fenced area.  I have a scene that turns on the house lights when someone "enters" the geofence, (by tripping the house to "home mode") but it doesn't work if someone else is already home :(  (because the house doen't flip to away mode unless ALL users have exited the geofence previously)

I was hoping I could use reactor to trip a virtual switch so that anytime a user with the defined geofence on their phone enters the geofence, it will turn on the lights. Prob isn't even necessary to flip house modes. I just want the "entry into a geofence" to execute a scene.

is there any geofence variables I can reference through reactor to accomplish this?

(if I should be posting this in the micasaverde forums, please advise! thanks!)

**Comment by toggledbits** [comment]
Hi there. The [Reactor board on the Vera forums](http://forum.micasaverde.com/index.php/board,93.0.html) is really the appropriate place for things like this. This "Issues" area is for bug reports, really.

To answer your question, the variables for geofencing would depend entirely on how you are doing your geofencing. But if there's a device with state variables about geofencing, Reactor can see it/them and let you act on them. If you take this over to the Vera forums, someone more knowledgeable on geofencing may chime in; I don't do it, so it's not an area I'm familiar with (except to read of the great pains user have in trying to get it right--partly why I stay away).
