### ISSUE TITLE
Status tab reporting incorrect status

### ISSUE THREAD

**Issue by Tarkus-NJ** [toggledbits/Reactor#20]
I started to put together a new sensor called TV Tuner Routine and I am using a ping sensor within a conditional group (device 97). The device tab is reporting it as being on when veras UI reports as correctly as on/off depending on the on/off state of my TV. Lua activity linked to group also not executing so I am assuming it is more than cosmetic. It is definitely stuck and not just delayed. I pulled a snippet after letting the device cycle on/off by powering on and off the TV. logic summary and snippet attached.

![Reactor_TV_Ping](https://user-images.githubusercontent.com/39711252/54881039-fd2d4300-4e21-11e9-9212-f0c8977c462b.png)

[TV Tuner Routine_Summary.txt](https://github.com/toggledbits/Reactor/files/3000486
/TV.Tuner.Routine_Summary.txt)
[Snippet4.txt](https://github.com/toggledbits/Reactor/files/3000488/Snippet4.txt)

**Comment by Tarkus-NJ** [comment]
Scratch this, solved, was set to configured instead of status.

**Comment by Tarkus-NJ** [comment]
Scratch that, solved had configured equals set instead of status, However there are some other issues, will report as new issue shortly.

**Comment by toggledbits** [comment]
This is the issue I referred to in issue #19. I've already fixed this. New beta package will go out later today. We'll leave this issue open for tracking and to signal the rest of the group that I'm aware of it.

**Comment by toggledbits** [comment]
Reactor Beta 3.0-19083 links have just been emailed to all beta participants. This version contains the fix for this bug.

**Comment by toggledbits** [comment]
Any concurrence? Is this resolved?

**Comment by Tarkus-NJ** [comment]
The problem I had encountered was because I I had the condition set to Configured equals instead of Status equals. So the issue is resolved.
