### ISSUE TITLE
True groups not executing activities

### ISSUE THREAD

**Issue by Tarkus-NJ** [toggledbits/Reactor#21]
Sensor TV Tuner Routine shows tripped and true conditional groups but does not execute attached activities. Snippet and Logic summary attached.

![Reactor_Activity_issue](https://user-images.githubusercontent.com/39711252/54882834-7cc40d80-4e34-11e9-96ff-5b3aa3a53bd4.png)

[TV.Tuner.Routine_Summary2.txt](https://github.com/toggledbits/Reactor/files/3000593/TV.Tuner.Routine_Summary2.txt)

[Snippet5.txt](https://github.com/toggledbits/Reactor/files/3000596/Snippet5.txt)

**Comment by toggledbits** [comment]
The summary attached shows the "Yamaha Input Routine" sensor, no the TV Tuner Routine.

In any case, the snippet has the same pattern that I saw in your other report, issue #19, so I'm to close this issue and continue on that thread.
