### ISSUE TITLE
getstate() insert tool fails to launch

### ISSUE THREAD

**Issue by BuxtonCalvin** [toggledbits/Reactor#23]
Hey Patrick,
I'm using Chrome on windows 10-- latest build-- for my client browser.  Running latest development openLuup with Altui on Armbian latest build.  Latest Beta Reactor ver 3.0beta-19083.

I'm trying to create some variables using the expression builder but there is no noticeable action occurring when I click on the Insert device state button. Attached are the logic report and screenshots.
[LogicSum.txt](https://github.com/toggledbits/Reactor/files/3010688/LogicSum.txt)
![2019-03-26 (1)](https://user-images.githubusercontent.com/23129738/55038034-d8c99600-4fdc-11e9-92db-77540fa03047.png)
![2019-03-26](https://user-images.githubusercontent.com/23129738/55038036-d8c99600-4fdc-11e9-96c1-4958a478ec74.png)

**Comment by toggledbits** [comment]
Now fixed in dev3.0 branch, will be in 19087 beta release later today.
