### ISSUE TITLE
Feature request to hide unused activity groups

### ISSUE THREAD

**Issue by Tarkus-NJ** [toggledbits/Reactor#24]
Feature request to hide unused activity groups to make for a cleaner UI. Perhaps a radio button on the group conditional or at the root of activities to toggle on/off.

**Comment by toggledbits** [comment]
Yeah... that list gets out of hand quickly, doesn't it?

**Comment by Tarkus-NJ** [comment]
Yes it does.

**Comment by toggledbits** [comment]
I haven't finished playing with this yet, so it didn't make it into 19087, but it will definitely make the next release.

**Comment by toggledbits** [comment]
After playing with it for a while, I've convinced myself that hiding unused activities isn't quite enough, so I've now got it where you can hide unused activities *and* collapse individual activities (same as collapsing conditions).

**Comment by toggledbits** [comment]
This is in 3.0beta-19090

**Comment by Tarkus-NJ** [comment]
This looks great Patrick.

Thank you!

**Comment by toggledbits** [comment]
BTW, the selected display mode, "All" or "In Use" should be persistent across all ReactorSensors (i.e. if you choose "In Use" while looking at ReactorSensor A, then that should be the display mode when you go in to ReactorSensor B).

I did not make the individual activity collapse states persistent, however.
