### ISSUE TITLE
Group Status Issue

### ISSUE THREAD

**Issue by Tarkus-NJ** [toggledbits/Reactor#27]
Patrick,

I am using group state to pick up the true or false status of a conditional group in a separate sensor. I am getting an unexpected false when the conditional group is showing true in originating sensor. Summary and snippet attached.

![Group_Status_Conflict](https://user-images.githubusercontent.com/39711252/55440959-3fb7f380-5577-11e9-9f41-b77764b43435.png)

[Snippet_Group_Condition.txt](https://github.com/toggledbits/Reactor/files/3036157/Snippet_Group_Condition.txt)
[Logic_Summary_Group_Condition.txt](https://github.com/toggledbits/Reactor/files/3036158/Logic_Summary_Group_Condition.txt)

**Comment by toggledbits** [comment]
OK. This is a simple fix. Rather than roll another beta for it just yet, I'll give you what should be the "less than one line" fix for it:

L_Reactor.lua line 2217 reads:
    `local vv = getVarNumeric( varname, 0, tdev, GRPSID ) ~= 0 -- boolean!`

Change the `tdev` to `cond.device`:
    `local vv = getVarNumeric( varname, 0, cond.device, GRPSID ) ~= 0 -- boolean!`

Then reload Luup.

**Comment by Tarkus-NJ** [comment]
Using Notepad++ it came up on line 2261. I searched for the string and it was the only line it was found on. The latest beta is reactor-beta3.0-19087, correct? Anyway I changed that line and problem is solved.

Thanks

**Comment by toggledbits** [comment]
Latest beta is 19090... miss the email? SPAM folder?

**Comment by Tarkus-NJ** [comment]
Exactly,, in spam folder. Will apply your fix before installing.

Thanks

**Comment by toggledbits** [comment]
In 19093
