### ISSUE TITLE
Interface issue, reordering conditional groups

### ISSUE THREAD

**Issue by Tarkus-NJ** [toggledbits/Reactor#28]
Patrick,

I had some issues with the drag and drop reordering feature in the condition tab. Upon moving groups or subgroups above other groups everything seemed fine, however after saving and leaving the tab, upon returning some of the groups below where gone or the group was still there but the variable content was gone. I was able to replicate this a few times.

John

**Comment by toggledbits** [comment]
OK. I think I may have this one. Very subtle, but not a one-line fix. I'll upload a new beta later today; I've got a busy afternoon, so look for the email after 7pm EDT.

**Comment by Tarkus-NJ** [comment]
I played around with a copy one of my more complex sensors and shuffled groups around. From as far as I can tell, it seems to be resolved.

**Comment by toggledbits** [comment]
In 19093
