### ISSUE TITLE
Can't detect device

### ISSUE THREAD

**Issue by Tarkus-NJ** [toggledbits/Reactor#29]
Hi Patrick,

Had this issue pop up spontaneously. Can't detect device across all sensors. Tried Vera soft and hard boot, restore from backup. I am on new beta since release and has been fine up until today. Log attached.

![device_detection_error](https://user-images.githubusercontent.com/39711252/55812576-3966d180-5ab9-11e9-83a1-8abb33714e34.png)

[veralog.txt](https://github.com/toggledbits/Reactor/files/3059716/veralog.txt)

**Comment by Tarkus-NJ** [comment]
Re-uploading the last reactor beta resolved issue. Looks like there was a missing or corrupt component. Will monitor to see if it happens again.

**Comment by toggledbits** [comment]
I know we already resolved this out of band, but for the sake of closure/documentation here:

Cause was Vera installing version 2.5 from the Plugin Marketplace when 3.0 was running. Configs are not backward compatible, so this is how 2.5 complains. It goes completely dead/offline, to avoid corrupting the higher version's config so the Vera can just be upgraded and party may resume.
