### ISSUE TITLE
Unable to delete conditions

### ISSUE THREAD

**Issue by Tarkus-NJ** [toggledbits/Reactor#32]
Hey Patrick,

I can't seem to delete conditions within a group but I can delete the whole group. This is happening across all sensors. I am able to delete condition groups just not individual conditions within groups. My work around is to change them to comments. I thought possibly if I moved problem conditions out of the group first then I would be able to delete but that did not work either.

**Comment by toggledbits** [comment]
What version are you running?

**Comment by Tarkus-NJ** [comment]
3.0beta-19093

**Comment by toggledbits** [comment]
OK. We're currently at 102, but I can't say that's been addressed. Sit tight. I'm looking at this; so far, I can't reproduce, but I'm big into code walk-throughs on issues like that.

**Comment by toggledbits** [comment]
There was a change to handleConditionDelete() 7 days ago (the stamp would have been 19097) that definitely would have caused the condition delete to trap, so if you still have 19093 installed, you should be able to observe the exception in the developers' console. But if you go to 19102, you should be good to go.

**Comment by Tarkus-NJ** [comment]
Can you resend 19102, checked spam and don't have it. I did a mass deletion of emails during the week so it may have been lost in the process.

**Comment by toggledbits** [comment]
I just posted 19104, which fixes another small issue with Revert. All versions since 19098 have been public on Github, in the "beta3.0" branch. Git ya some!

**Comment by toggledbits** [comment]
I'm going to go ahead and mark this as a bug even though it's already fixed (I think), and leave it open, in case anything else comes up that's close.

**Comment by Tarkus-NJ** [comment]
Seems to be fixed with 19104
