### ISSUE TITLE
delay timer

### ISSUE THREAD

**Issue by Djkelley88** [toggledbits/Reactor#40]
I want to Turn "on" a light when a door is open and leave the light on for 8 minutes and I can not get that to work. Can you help me with that?

**Comment by toggledbits** [comment]
OK. First, have a look at this video: https://youtu.be/VBr4gBcgQRg

Your problem, in its simplest form, can be solved with a single condition to which you add a reset delay. I'll leave it at that for now, and between that suggestion and the video, let's see how you fare. If you need additional direction, chime in here.

**Comment by toggledbits** [comment]
How have you made out with this?
