### ISSUE TITLE
values change in activity

### ISSUE THREAD

**Issue by prophead** [toggledbits/Reactor#52]
This is clearly a bug.  3.5 hotfix on AltUI.  I have 7 groups, so 8 sets of t/f activities on my sensor.  Each of the true activities sends a different email.  Whenever I save my sensor it reverts all the email messages to the last one.  In other words I cannot save 7 independent email messages from the activities tab.

**Comment by prophead** [comment]
Semi-solved, this problem was a result of copying activities and then changing them, apparently it kept referenced the original, I just had to make new notify activities, problem solved

**Comment by toggledbits** [comment]
Fixed for 3.6
